version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant  # Specify the version of Qdrant you want to use
    container_name: qdrant
    ports:
      - "6333:6333"  # Expose HTTP port
      - "6334:6334"  # Expose gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
  postgres:
    image: timescale/timescaledb:2.14.2-pg16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # MinIO web UI and API
      - "9001:9001"   # MinIO Console (optional)
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"



volumes:
  qdrant_data:
    driver: local
  postgres_data:
    driver: local
  minio_data:
    driver: local
