version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant  # Specify the version of Qdrant you want to use
    container_name: qdrant
    ports:
      - "6333:6333"  # Expose HTTP port
      - "6334:6334"  # Expose gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
  postgres:
    image: timescale/timescaledb:2.14.2-pg16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  qdrant_data:
    driver: local
  postgres_data:
    driver: local
